### ISSUE TITLE
How configure the size of the image?

### ISSUE THREAD

**Issue by Nicky282** [yue-zhongqi/gcm-cf#9]
I want to change the size of the image to 64*64, but I encountered some problems:
"""
GARBAGE40
Experiment: GARBAGE40-baseline-lamda100
Begin to Run Exp 0...
decreasing_lr: [60, 100, 150]
Training... Epoch = 0
Traceback (most recent call last):
  File "D:/a全部文件/科研 竞赛 项目/南京理工研究生项目/新类检测/OSR/基于DNN的OSR方法/Code/复现/gcm-cf-main/gcm-cf-main/osr/lvae_train.py", line 461, in <module>
    best_val_loss, best_val_epoch = train(args, lvae)
  File "D:/a全部文件/科研 竞赛 项目/南京理工研究生项目/新类检测/OSR/基于DNN的OSR方法/Code/复现/gcm-cf-main/gcm-cf-main/osr/lvae_train.py", line 130, in train
    loss, mu, output, output_mu, x_re, rec, kl, ce = lvae.loss(data, target, target_en, next(beta), args.lamda, args)
  File "D:\a全部文件\科研 竞赛 项目\南京理工研究生项目\新类检测\OSR\基于DNN的OSR方法\Code\复现\gcm-cf-main\gcm-cf-main\osr\model.py", line 342, in loss
    pmu2_2, pvar2_2, pmu2_1, pvar2_1, pmu1_2, pvar1_2, pmu1_1, pvar1_1 = self.lnet(x, y_de, args)
  File "D:\a全部文件\科研 竞赛 项目\南京理工研究生项目\新类检测\OSR\基于DNN的OSR方法\Code\复现\gcm-cf-main\gcm-cf-main\osr\model.py", line 243, in lnet
    predict = F.log_softmax(self.classifier(latent_y), dim=1)
  File "C:\Users\296714435\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\296714435\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\296714435\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
 ** On entry to SGEMM  parameter number 10 had an illegal value
"""

**Comment by ShellyShellyShellyShelly** [comment]
请问你的问题解决了吗，我也想改图片尺寸

**Comment by Wangt-CN** [comment]
Hi, @Nicky282, thanks for your interests. Our code is built on CGDL by fixing its code bug. Actually, CGDL itself does not support dynamic input size and we just follow it to run the experiments. However, after checking your output info, it seemed that you need to modify the CNN config of the CGDL framework to support the image size of 64. Hope this helps.
